#!/usr/bin/env bash
## Configure my domain zone:
## www --> 465493-lb-01 54.236.43.155
## web-01 --> 465493-web-01 18.204.10.176
## web-02 --> 465493-web-02 34.227.101.135
#
#subdomains_all=("www" "lb-01" "web-01" "web-02")
#
#runDig() {
#    subdomain=$1
#        domain=$2
#
#            dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
#            }
#
#            if [ $# -eq 1 ]; then
#                domain="$1"
#                    for i in "${subdomains_all[@]}"; do
#                            runDig "$i" "$domain"
#                                done
#                                elif [ $# -eq 2 ]; then
#                                    domain="$1"
#                                        subdomain="$2"
#                                            runDig "$subdomain" "$domain"
#                                            fi
