#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create HTML directory
sudo mkdir -p /etc/nginx/html

# Create index.html
echo "Holberton School" | sudo tee /etc/nginx/html/index.html

# Create 404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Configure Nginx
echo "server {
    listen 80 default_server;
        listen [::]:80 default_server;
	    root /etc/nginx/html;
	        index index.html;
		    location /redirect_me {
		            return 301 https://twitter.com/Emmanue17280546;
			        }
				    error_page 404 /404.html;
				        location = /404.html {
					        root /etc/nginx/html;
						        internal;
							    }
						    }" | sudo tee /etc/nginx/sites-available/default

						    # Restart Nginx
						    sudo service nginx restart
