#!/bin/bash

# Specify the name of the private key
private_key="school"

# Specify the number of bits in the key
bits=4096

# Specify the passphrase
passphrase="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b "$bits" -f "$private_key" -N "$passphrase"

# Display information about the generated key pair
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in ${private_key}.pub."
echo "The key fingerprint is:"
ssh-keygen -lf "$private_key"
echo "The key's randomart image is:"
ssh-keygen -l -v -f "$private_key"
